# -*- coding: utf-8 -*-
"""samp data set .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQg8zPACcNvz4vsgKkyccILEqAEsfFNU
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import streamlit as st

#load data
data = pd.read_csv("/content/spam.csv")

data.drop_duplicates(inplace = True)

data['Category'] = data['Category'].replace(['ham', 'spam'], ['Not Spam', "Spam"])

mess = data['Message']
cat = data['Category']

mess_train, mess_test, cat_train, cat_test = train_test_split(mess, cat, test_size=0.2, random_state=42)

cv = CountVectorizer(stop_words='english')
features_train = cv.fit_transform(mess_train)
features_test = cv.transform(mess_test)

#creating Model
model = MultinomialNB()
model.fit(features_train, cat_train)

#Test our model
features_test = cv.transform(mess_test)
#print(model.score(features_test, cat_test))

#predict Data
def predict(message):
  input_message = cv.transform([message]).toarray()
  result = model.predict(input_message)
  return result
st.header('Spam Detection')

output = predict('Congratulations, you won a lottery')
input_messge = st.text_input('Enter Message Here')

if st.button('Validate'):
  output = predict(input_mess)
  st.text = output